### ISSUE TITLE
Projects which can be used as examples in docs

### ISSUE THREAD

**Issue by pepe** [funcool/potok#1]
Hello, first of all, thank you very much for this library. It is pure joy to work with it for me.

But I opened this issue, to let you know that I created two open projects, where I am using it, and which maybe can be added to documentation as examples:

- Potok Rumu https://github.com/pepe/potok-rumu, which I created to get notion of how Potok works
- Showrum https://github.com/pepe/showrum, which is my presentation SW written in ClojureScript, recently moved to Potok

If you agree, I would create PR.

Again thank you very much, I am actually working on proposal for Polyconf, where I would like to present the philosophy behind Potok.

**Comment by niwinz** [comment]
Please, open a PR, and I'm gladly accept it.

**Comment by niwinz** [comment]
And thank you very much for your words!

**Comment by pepe** [comment]
Great! I wll do tonite. 

Thank you so much!
